/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VirtualPiano;

import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author Mifthulyn07
 */
public class VirtualPiano extends javax.swing.JFrame {

    /**
     * Creates new form VirtualPiano
     */
    public VirtualPiano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jchkMusic = new javax.swing.JCheckBox();
        jchkSteel = new javax.swing.JCheckBox();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Virtual Piano");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 30, 630, 90);

        buttonGroup1.add(jchkMusic);
        jchkMusic.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jchkMusic.setForeground(java.awt.Color.white);
        jchkMusic.setText("Music Notes");
        jPanel1.add(jchkMusic);
        jchkMusic.setBounds(50, 140, 260, 60);

        buttonGroup1.add(jchkSteel);
        jchkSteel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jchkSteel.setForeground(java.awt.Color.white);
        jchkSteel.setText("Steel Drum");
        jPanel1.add(jchkSteel);
        jchkSteel.setBounds(800, 150, 240, 60);

        jButton12.setBackground(java.awt.Color.black);
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(java.awt.Color.white);
        jButton12.setText("C#");
        jButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(100, 250, 70, 150);

        jButton14.setBackground(java.awt.Color.black);
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setForeground(java.awt.Color.white);
        jButton14.setText("F#");
        jButton14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(370, 250, 70, 150);

        jButton15.setBackground(java.awt.Color.black);
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setForeground(java.awt.Color.white);
        jButton15.setText("G#");
        jButton15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(460, 250, 70, 150);

        jButton4.setBackground(java.awt.Color.white);
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("F");
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(330, 250, 70, 310);

        jButton13.setBackground(java.awt.Color.black);
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setForeground(java.awt.Color.white);
        jButton13.setText("D#");
        jButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(190, 250, 70, 150);

        jButton16.setBackground(java.awt.Color.black);
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton16.setForeground(java.awt.Color.white);
        jButton16.setText("Bb");
        jButton16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(560, 250, 70, 150);

        jButton5.setBackground(java.awt.Color.white);
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("G");
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(420, 250, 70, 310);

        jButton3.setBackground(java.awt.Color.white);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("E");
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 250, 70, 310);

        jButton17.setBackground(java.awt.Color.black);
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setForeground(java.awt.Color.white);
        jButton17.setText("D#1");
        jButton17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(740, 250, 70, 150);

        jButton7.setBackground(java.awt.Color.white);
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("B");
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(600, 250, 70, 310);

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("D");
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 250, 70, 310);

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("C");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 250, 70, 310);

        jButton6.setBackground(java.awt.Color.white);
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("A");
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(510, 250, 70, 310);

        jButton8.setBackground(java.awt.Color.white);
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText("C1");
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(690, 250, 70, 310);

        jButton18.setBackground(java.awt.Color.black);
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton18.setForeground(java.awt.Color.white);
        jButton18.setText("D#1");
        jButton18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(830, 250, 70, 150);

        jButton10.setBackground(java.awt.Color.white);
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setText("E1");
        jButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(870, 250, 70, 310);

        jButton9.setBackground(java.awt.Color.white);
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("D1");
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(780, 250, 70, 310);

        jButton11.setBackground(java.awt.Color.white);
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton11.setText("F1");
        jButton11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(960, 250, 70, 310);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 620);

        setSize(new java.awt.Dimension(1106, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.BLACK);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InputStream iAudio;
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\C.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }}
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\C_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\D.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\D_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\E.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\E_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\F.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\F_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\G.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\G_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\A.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\A_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\B.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\B_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\C1.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\C1_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\D1.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\D1_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\E1.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\E1_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\F.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\F1_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\C_s.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\Cq_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\D_s.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\Dq_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\F_s.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\Fq_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\G_s.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\Gq_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\Bb.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\Bb_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\C_s1.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\Cq1_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        InputStream iAudio;
        
        if (jchkMusic.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\D_s1.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if (jchkSteel.isSelected()){
            try {
                iAudio = new FileInputStream(new File("D:\\Programming\\percobaan\\CobaJava\\Virtual_Piano_Keys\\Music_Note\\Dq1_Drum.wav"));
                AudioStream iMusic = new AudioStream (iAudio);
                AudioPlayer.player.start(iMusic);
            }
            
            catch (IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirtualPiano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jchkMusic;
    private javax.swing.JCheckBox jchkSteel;
    // End of variables declaration//GEN-END:variables
}
